const ex = {
  location: {
    name: "Milan",
    region: "Lombardia",
    country: "Italy",
    lat: 45.47,
    lon: 9.2,
    tz_id: "Europe/Rome",
    localtime_epoch: 1720880966,
    localtime: "2024-07-13 16:29",
  },
  current: {
    last_updated_epoch: 1720880100,
    last_updated: "2024-07-13 16:15",
    temp_c: 30.3,
    temp_f: 86.5,
    is_day: 1,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003,
    },
    wind_mph: 6.9,
    wind_kph: 11.2,
    wind_degree: 260,
    wind_dir: "W",
    pressure_mb: 1009,
    pressure_in: 29.8,
    precip_mm: 0.01,
    precip_in: 0,
    humidity: 52,
    cloud: 50,
    feelslike_c: 33.8,
    feelslike_f: 92.9,
    windchill_c: 27.8,
    windchill_f: 82.1,
    heatindex_c: 29.6,
    heatindex_f: 85.2,
    dewpoint_c: 19.6,
    dewpoint_f: 67.3,
    vis_km: 10,
    vis_miles: 6,
    uv: 6,
    gust_mph: 11.4,
    gust_kph: 18.4,
  },
  forecast: {
    forecastday: [
      {
        date: "2024-07-13",
        date_epoch: 1720828800,
        day: {
          maxtemp_c: 27.9,
          maxtemp_f: 82.2,
          mintemp_c: 19.5,
          mintemp_f: 67.2,
          avgtemp_c: 22.9,
          avgtemp_f: 73.2,
          maxwind_mph: 4.5,
          maxwind_kph: 7.2,
          totalprecip_mm: 4.83,
          totalprecip_in: 0.19,
          totalsnow_cm: 0,
          avgvis_km: 7.8,
          avgvis_miles: 4,
          avghumidity: 84,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 94,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain nearby",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 8,
        },
        astro: {
          sunrise: "05:48 AM",
          sunset: "09:10 PM",
          moonrise: "01:25 PM",
          moonset: "12:18 AM",
          moon_phase: "First Quarter",
          moon_illumination: 41,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1720821600,
            time: "2024-07-13 00:00",
            temp_c: 21.2,
            temp_f: 70.1,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 264,
            wind_dir: "W",
            pressure_mb: 1009,
            pressure_in: 29.8,
            precip_mm: 0.04,
            precip_in: 0,
            snow_cm: 0,
            humidity: 92,
            cloud: 73,
            feelslike_c: 21.2,
            feelslike_f: 70.1,
            windchill_c: 21.2,
            windchill_f: 70.1,
            heatindex_c: 24.2,
            heatindex_f: 75.5,
            dewpoint_c: 19.9,
            dewpoint_f: 67.7,
            will_it_rain: 0,
            chance_of_rain: 63,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.6,
            uv: 0,
            short_rad: 8.88,
            diff_rad: 4.1,
          },
          {
            time_epoch: 1720825200,
            time: "2024-07-13 01:00",
            temp_c: 20.7,
            temp_f: 69.3,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 281,
            wind_dir: "WNW",
            pressure_mb: 1009,
            pressure_in: 29.8,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 94,
            cloud: 28,
            feelslike_c: 20.7,
            feelslike_f: 69.3,
            windchill_c: 20.7,
            windchill_f: 69.3,
            heatindex_c: 20.7,
            heatindex_f: 69.3,
            dewpoint_c: 19.7,
            dewpoint_f: 67.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.4,
            gust_kph: 13.5,
            uv: 0,
            short_rad: 7.39,
            diff_rad: 3.42,
          },
          {
            time_epoch: 1720828800,
            time: "2024-07-13 02:00",
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 287,
            wind_dir: "WNW",
            pressure_mb: 1009,
            pressure_in: 29.79,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 95,
            cloud: 38,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 19.7,
            dewpoint_f: 67.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 7.3,
            gust_kph: 11.7,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1720832400,
            time: "2024-07-13 03:00",
            temp_c: 20.3,
            temp_f: 68.5,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 287,
            wind_dir: "WNW",
            pressure_mb: 1009,
            pressure_in: 29.79,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 95,
            cloud: 57,
            feelslike_c: 20.3,
            feelslike_f: 68.5,
            windchill_c: 20.3,
            windchill_f: 68.5,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 19.5,
            dewpoint_f: 67,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.4,
            gust_kph: 10.3,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1720836000,
            time: "2024-07-13 04:00",
            temp_c: 20,
            temp_f: 67.9,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 287,
            wind_dir: "WNW",
            pressure_mb: 1009,
            pressure_in: 29.79,
            precip_mm: 0.64,
            precip_in: 0.03,
            snow_cm: 0,
            humidity: 95,
            cloud: 79,
            feelslike_c: 20,
            feelslike_f: 67.9,
            windchill_c: 20,
            windchill_f: 67.9,
            heatindex_c: 20,
            heatindex_f: 67.9,
            dewpoint_c: 19.2,
            dewpoint_f: 66.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5,
            vis_miles: 3,
            gust_mph: 4.2,
            gust_kph: 6.7,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1720839600,
            time: "2024-07-13 05:00",
            temp_c: 19.5,
            temp_f: 67.2,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 267,
            wind_dir: "W",
            pressure_mb: 1009,
            pressure_in: 29.8,
            precip_mm: 0.65,
            precip_in: 0.03,
            snow_cm: 0,
            humidity: 96,
            cloud: 65,
            feelslike_c: 19.5,
            feelslike_f: 67.2,
            windchill_c: 19.5,
            windchill_f: 67.2,
            heatindex_c: 19.5,
            heatindex_f: 67.2,
            dewpoint_c: 18.9,
            dewpoint_f: 66.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5,
            vis_miles: 3,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 0,
            short_rad: 0.08,
            diff_rad: 0.04,
          },
          {
            time_epoch: 1720843200,
            time: "2024-07-13 06:00",
            temp_c: 19.8,
            temp_f: 67.7,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 250,
            wind_dir: "WSW",
            pressure_mb: 1009,
            pressure_in: 29.81,
            precip_mm: 0.33,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 96,
            cloud: 70,
            feelslike_c: 19.8,
            feelslike_f: 67.7,
            windchill_c: 19.8,
            windchill_f: 67.7,
            heatindex_c: 19.8,
            heatindex_f: 67.7,
            dewpoint_c: 19.2,
            dewpoint_f: 66.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.3,
            gust_kph: 5.3,
            uv: 4,
            short_rad: 9.36,
            diff_rad: 4.48,
          },
          {
            time_epoch: 1720846800,
            time: "2024-07-13 07:00",
            temp_c: 20.3,
            temp_f: 68.6,
            is_day: 1,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
              code: 1153,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 271,
            wind_dir: "W",
            pressure_mb: 1010,
            pressure_in: 29.82,
            precip_mm: 0.41,
            precip_in: 0.02,
            snow_cm: 0,
            humidity: 95,
            cloud: 85,
            feelslike_c: 20.3,
            feelslike_f: 68.6,
            windchill_c: 20.3,
            windchill_f: 68.6,
            heatindex_c: 20.3,
            heatindex_f: 68.6,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 3.9,
            gust_kph: 6.3,
            uv: 5,
            short_rad: 24.19,
            diff_rad: 11.83,
          },
          {
            time_epoch: 1720850400,
            time: "2024-07-13 08:00",
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 1,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
              code: 1030,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 296,
            wind_dir: "WNW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0.11,
            precip_in: 0,
            snow_cm: 0,
            humidity: 94,
            cloud: 70,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 19.7,
            dewpoint_f: 67.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 4.2,
            gust_kph: 6.8,
            uv: 5,
            short_rad: 95.04,
            diff_rad: 53.81,
          },
          {
            time_epoch: 1720854000,
            time: "2024-07-13 09:00",
            temp_c: 21.4,
            temp_f: 70.5,
            is_day: 1,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/263.png",
              code: 1150,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 315,
            wind_dir: "NW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0.48,
            precip_in: 0.02,
            snow_cm: 0,
            humidity: 92,
            cloud: 64,
            feelslike_c: 21.4,
            feelslike_f: 70.5,
            windchill_c: 21.4,
            windchill_f: 70.5,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 20,
            dewpoint_f: 68,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5,
            vis_miles: 3,
            gust_mph: 2.8,
            gust_kph: 4.4,
            uv: 5,
            short_rad: 126.22,
            diff_rad: 71.6,
          },
          {
            time_epoch: 1720857600,
            time: "2024-07-13 10:00",
            temp_c: 21.5,
            temp_f: 70.7,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 217,
            wind_dir: "SW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0.53,
            precip_in: 0.02,
            snow_cm: 0,
            humidity: 92,
            cloud: 89,
            feelslike_c: 21.5,
            feelslike_f: 70.7,
            windchill_c: 21.5,
            windchill_f: 70.7,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 20.1,
            dewpoint_f: 68.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 6.1,
            gust_kph: 9.8,
            uv: 5,
            short_rad: 112.72,
            diff_rad: 65.84,
          },
          {
            time_epoch: 1720861200,
            time: "2024-07-13 11:00",
            temp_c: 22.7,
            temp_f: 72.8,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 244,
            wind_dir: "WSW",
            pressure_mb: 1010,
            pressure_in: 29.84,
            precip_mm: 0.57,
            precip_in: 0.02,
            snow_cm: 0,
            humidity: 87,
            cloud: 83,
            feelslike_c: 24.9,
            feelslike_f: 76.9,
            windchill_c: 22.7,
            windchill_f: 72.8,
            heatindex_c: 24.9,
            heatindex_f: 76.9,
            dewpoint_c: 20.4,
            dewpoint_f: 68.8,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 4.6,
            gust_kph: 7.3,
            uv: 5,
            short_rad: 184.52,
            diff_rad: 103.28,
          },
          {
            time_epoch: 1720864800,
            time: "2024-07-13 12:00",
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 253,
            wind_dir: "WSW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0.2,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 78,
            cloud: 83,
            feelslike_c: 26.5,
            feelslike_f: 79.7,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 26.5,
            heatindex_f: 79.7,
            dewpoint_c: 20.5,
            dewpoint_f: 68.9,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 3.2,
            gust_kph: 5.2,
            uv: 5,
            short_rad: 309.76,
            diff_rad: 133.17,
          },
          {
            time_epoch: 1720868400,
            time: "2024-07-13 13:00",
            temp_c: 26.4,
            temp_f: 79.6,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 169,
            wind_dir: "S",
            pressure_mb: 1010,
            pressure_in: 29.82,
            precip_mm: 0.02,
            precip_in: 0,
            snow_cm: 0,
            humidity: 69,
            cloud: 80,
            feelslike_c: 28.3,
            feelslike_f: 82.9,
            windchill_c: 26.4,
            windchill_f: 79.6,
            heatindex_c: 28.3,
            heatindex_f: 82.9,
            dewpoint_c: 20.2,
            dewpoint_f: 68.4,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.4,
            gust_kph: 2.2,
            uv: 6,
            short_rad: 403.36,
            diff_rad: 141.88,
          },
          {
            time_epoch: 1720872000,
            time: "2024-07-13 14:00",
            temp_c: 26.9,
            temp_f: 80.5,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 162,
            wind_dir: "SSE",
            pressure_mb: 1010,
            pressure_in: 29.82,
            precip_mm: 0.11,
            precip_in: 0,
            snow_cm: 0,
            humidity: 68,
            cloud: 71,
            feelslike_c: 28.9,
            feelslike_f: 84,
            windchill_c: 26.9,
            windchill_f: 80.5,
            heatindex_c: 28.9,
            heatindex_f: 84,
            dewpoint_c: 20.4,
            dewpoint_f: 68.8,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.8,
            gust_kph: 2.9,
            uv: 6,
            short_rad: 859.7,
            diff_rad: 147.88,
          },
          {
            time_epoch: 1720875600,
            time: "2024-07-13 15:00",
            temp_c: 27.9,
            temp_f: 82.2,
            is_day: 1,
            condition: {
              text: "Thundery outbreaks in nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/200.png",
              code: 1087,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 81,
            wind_dir: "E",
            pressure_mb: 1009,
            pressure_in: 29.81,
            precip_mm: 0.08,
            precip_in: 0,
            snow_cm: 0,
            humidity: 62,
            cloud: 89,
            feelslike_c: 29.8,
            feelslike_f: 85.6,
            windchill_c: 27.9,
            windchill_f: 82.2,
            heatindex_c: 29.8,
            heatindex_f: 85.6,
            dewpoint_c: 19.9,
            dewpoint_f: 67.7,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 1.6,
            gust_kph: 2.5,
            uv: 6,
            short_rad: 824.68,
            diff_rad: 134.77,
          },
          {
            time_epoch: 1720879200,
            time: "2024-07-13 16:00",
            temp_c: 30.3,
            temp_f: 86.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 1009,
            pressure_in: 29.8,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 52,
            cloud: 50,
            feelslike_c: 29.6,
            feelslike_f: 85.2,
            windchill_c: 27.8,
            windchill_f: 82.1,
            heatindex_c: 29.6,
            heatindex_f: 85.2,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.4,
            gust_kph: 18.4,
            uv: 6,
            short_rad: 755.76,
            diff_rad: 161.14,
          },
          {
            time_epoch: 1720882800,
            time: "2024-07-13 17:00",
            temp_c: 27.5,
            temp_f: 81.4,
            is_day: 1,
            condition: {
              text: "Thundery outbreaks in nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/200.png",
              code: 1087,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 88,
            wind_dir: "E",
            pressure_mb: 1009,
            pressure_in: 29.79,
            precip_mm: 0.09,
            precip_in: 0,
            snow_cm: 0,
            humidity: 63,
            cloud: 86,
            feelslike_c: 29.2,
            feelslike_f: 84.6,
            windchill_c: 27.5,
            windchill_f: 81.4,
            heatindex_c: 29.2,
            heatindex_f: 84.6,
            dewpoint_c: 19.7,
            dewpoint_f: 67.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 2.3,
            gust_kph: 3.7,
            uv: 6,
            short_rad: 679.36,
            diff_rad: 168.34,
          },
          {
            time_epoch: 1720886400,
            time: "2024-07-13 18:00",
            temp_c: 26.9,
            temp_f: 80.4,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 64,
            wind_dir: "ENE",
            pressure_mb: 1009,
            pressure_in: 29.79,
            precip_mm: 0.15,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 69,
            cloud: 89,
            feelslike_c: 29,
            feelslike_f: 84.1,
            windchill_c: 26.9,
            windchill_f: 80.3,
            heatindex_c: 29,
            heatindex_f: 84.1,
            dewpoint_c: 20.8,
            dewpoint_f: 69.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.8,
            gust_kph: 4.5,
            uv: 6,
            short_rad: 613.2,
            diff_rad: 153.01,
          },
          {
            time_epoch: 1720890000,
            time: "2024-07-13 19:00",
            temp_c: 24.9,
            temp_f: 76.8,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 333,
            wind_dir: "NNW",
            pressure_mb: 1009,
            pressure_in: 29.8,
            precip_mm: 0.18,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 79,
            cloud: 89,
            feelslike_c: 26.9,
            feelslike_f: 80.4,
            windchill_c: 24.9,
            windchill_f: 76.8,
            heatindex_c: 26.9,
            heatindex_f: 80.4,
            dewpoint_c: 21.1,
            dewpoint_f: 69.9,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.7,
            gust_kph: 5.9,
            uv: 5,
            short_rad: 541.6,
            diff_rad: 137.23,
          },
          {
            time_epoch: 1720893600,
            time: "2024-07-13 20:00",
            temp_c: 23,
            temp_f: 73.5,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 338,
            wind_dir: "NNW",
            pressure_mb: 1009,
            pressure_in: 29.81,
            precip_mm: 0.21,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 84,
            cloud: 74,
            feelslike_c: 25.2,
            feelslike_f: 77.3,
            windchill_c: 23,
            windchill_f: 73.5,
            heatindex_c: 25.2,
            heatindex_f: 77.3,
            dewpoint_c: 20.1,
            dewpoint_f: 68.3,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.6,
            gust_kph: 10.6,
            uv: 5,
            short_rad: 44.38,
            diff_rad: 20.05,
          },
          {
            time_epoch: 1720897200,
            time: "2024-07-13 21:00",
            temp_c: 22.1,
            temp_f: 71.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 341,
            wind_dir: "NNW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 9,
            feelslike_c: 24.5,
            feelslike_f: 76.2,
            windchill_c: 22.1,
            windchill_f: 71.7,
            heatindex_c: 24.5,
            heatindex_f: 76.2,
            dewpoint_c: 19.9,
            dewpoint_f: 67.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 6,
            short_rad: 22.24,
            diff_rad: 10.05,
          },
          {
            time_epoch: 1720900800,
            time: "2024-07-13 22:00",
            temp_c: 21.6,
            temp_f: 70.8,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 334,
            wind_dir: "NNW",
            pressure_mb: 1011,
            pressure_in: 29.84,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 89,
            feelslike_c: 21.6,
            feelslike_f: 70.8,
            windchill_c: 21.6,
            windchill_f: 70.8,
            heatindex_c: 24.3,
            heatindex_f: 75.8,
            dewpoint_c: 19.7,
            dewpoint_f: 67.4,
            will_it_rain: 1,
            chance_of_rain: 71,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
            short_rad: 14.82,
            diff_rad: 6.7,
          },
          {
            time_epoch: 1720904400,
            time: "2024-07-13 23:00",
            temp_c: 21,
            temp_f: 69.8,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 320,
            wind_dir: "NW",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 34,
            feelslike_c: 21,
            feelslike_f: 69.8,
            windchill_c: 21,
            windchill_f: 69.8,
            heatindex_c: 24.2,
            heatindex_f: 75.5,
            dewpoint_c: 19.2,
            dewpoint_f: 66.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.6,
            uv: 0,
            short_rad: 11.12,
            diff_rad: 5.02,
          },
        ],
      },
      {
        date: "2024-07-14",
        date_epoch: 1720915200,
        day: {
          maxtemp_c: 29,
          maxtemp_f: 84.3,
          mintemp_c: 19.2,
          mintemp_f: 66.5,
          avgtemp_c: 24.2,
          avgtemp_f: 75.5,
          maxwind_mph: 4.3,
          maxwind_kph: 6.8,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 71,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 8,
        },
        astro: {
          sunrise: "05:49 AM",
          sunset: "09:09 PM",
          moonrise: "02:29 PM",
          moonset: "12:33 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: 50,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1720908000,
            time: "2024-07-14 00:00",
            temp_c: 20.5,
            temp_f: 69,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 302,
            wind_dir: "WNW",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 90,
            cloud: 42,
            feelslike_c: 20.5,
            feelslike_f: 69,
            windchill_c: 20.5,
            windchill_f: 69,
            heatindex_c: 20.5,
            heatindex_f: 69,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12.1,
            uv: 0,
            short_rad: 8.9,
            diff_rad: 4.02,
          },
          {
            time_epoch: 1720911600,
            time: "2024-07-14 01:00",
            temp_c: 20.3,
            temp_f: 68.6,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 296,
            wind_dir: "WNW",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 33,
            feelslike_c: 20.3,
            feelslike_f: 68.6,
            windchill_c: 20.3,
            windchill_f: 68.6,
            heatindex_c: 20.3,
            heatindex_f: 68.6,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.3,
            gust_kph: 11.7,
            uv: 0,
            short_rad: 7.41,
            diff_rad: 3.35,
          },
          {
            time_epoch: 1720915200,
            time: "2024-07-14 02:00",
            temp_c: 20.1,
            temp_f: 68.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 291,
            wind_dir: "WNW",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 24,
            feelslike_c: 20.1,
            feelslike_f: 68.2,
            windchill_c: 20.1,
            windchill_f: 68.2,
            heatindex_c: 20.1,
            heatindex_f: 68.2,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.1,
            gust_kph: 11.4,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1720918800,
            time: "2024-07-14 03:00",
            temp_c: 19.9,
            temp_f: 67.8,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 276,
            wind_dir: "W",
            pressure_mb: 1011,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 27,
            feelslike_c: 19.9,
            feelslike_f: 67.8,
            windchill_c: 19.9,
            windchill_f: 67.8,
            heatindex_c: 19.9,
            heatindex_f: 67.8,
            dewpoint_c: 17.8,
            dewpoint_f: 64,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.7,
            gust_kph: 9.2,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1720922400,
            time: "2024-07-14 04:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 277,
            wind_dir: "W",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 22,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 17.5,
            dewpoint_f: 63.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.3,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1720926000,
            time: "2024-07-14 05:00",
            temp_c: 19.2,
            temp_f: 66.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 279,
            wind_dir: "W",
            pressure_mb: 1011,
            pressure_in: 29.86,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 22,
            feelslike_c: 19.2,
            feelslike_f: 66.5,
            windchill_c: 19.2,
            windchill_f: 66.5,
            heatindex_c: 19.2,
            heatindex_f: 66.5,
            dewpoint_c: 17.3,
            dewpoint_f: 63.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.3,
            gust_kph: 8.6,
            uv: 0,
            short_rad: 0.06,
            diff_rad: 0.02,
          },
          {
            time_epoch: 1720929600,
            time: "2024-07-14 06:00",
            temp_c: 20,
            temp_f: 68,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 281,
            wind_dir: "WNW",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 26,
            feelslike_c: 20,
            feelslike_f: 68,
            windchill_c: 20,
            windchill_f: 68,
            heatindex_c: 20,
            heatindex_f: 68,
            dewpoint_c: 17.9,
            dewpoint_f: 64.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.5,
            gust_kph: 8.9,
            uv: 5,
            short_rad: 7.55,
            diff_rad: 3.77,
          },
          {
            time_epoch: 1720933200,
            time: "2024-07-14 07:00",
            temp_c: 21.3,
            temp_f: 70.4,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 280,
            wind_dir: "W",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 81,
            cloud: 29,
            feelslike_c: 21.3,
            feelslike_f: 70.4,
            windchill_c: 21.3,
            windchill_f: 70.4,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 18,
            dewpoint_f: 64.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.2,
            gust_kph: 5.2,
            uv: 6,
            short_rad: 34.29,
            diff_rad: 15.13,
          },
          {
            time_epoch: 1720936800,
            time: "2024-07-14 08:00",
            temp_c: 22.8,
            temp_f: 73.1,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 256,
            wind_dir: "WSW",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 74,
            cloud: 29,
            feelslike_c: 24.9,
            feelslike_f: 76.9,
            windchill_c: 22.8,
            windchill_f: 73.1,
            heatindex_c: 24.9,
            heatindex_f: 76.9,
            dewpoint_c: 17.9,
            dewpoint_f: 64.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.8,
            gust_kph: 4.4,
            uv: 6,
            short_rad: 359.24,
            diff_rad: 84.67,
          },
          {
            time_epoch: 1720940400,
            time: "2024-07-14 09:00",
            temp_c: 24.2,
            temp_f: 75.6,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 242,
            wind_dir: "WSW",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 69,
            cloud: 29,
            feelslike_c: 25.8,
            feelslike_f: 78.5,
            windchill_c: 24.2,
            windchill_f: 75.6,
            heatindex_c: 25.8,
            heatindex_f: 78.5,
            dewpoint_c: 18.1,
            dewpoint_f: 64.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.9,
            gust_kph: 6.2,
            uv: 6,
            short_rad: 443.74,
            diff_rad: 93.39,
          },
          {
            time_epoch: 1720944000,
            time: "2024-07-14 10:00",
            temp_c: 25.6,
            temp_f: 78.1,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 256,
            wind_dir: "WSW",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 64,
            cloud: 27,
            feelslike_c: 27,
            feelslike_f: 80.5,
            windchill_c: 25.6,
            windchill_f: 78.1,
            heatindex_c: 27,
            heatindex_f: 80.5,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 7,
            short_rad: 521.88,
            diff_rad: 99.92,
          },
          {
            time_epoch: 1720947600,
            time: "2024-07-14 11:00",
            temp_c: 26.9,
            temp_f: 80.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 246,
            wind_dir: "WSW",
            pressure_mb: 1012,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 60,
            cloud: 23,
            feelslike_c: 28.2,
            feelslike_f: 82.8,
            windchill_c: 26.9,
            windchill_f: 80.4,
            heatindex_c: 28.2,
            heatindex_f: 82.8,
            dewpoint_c: 18.5,
            dewpoint_f: 65.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 7,
            short_rad: 590.08,
            diff_rad: 104.81,
          },
          {
            time_epoch: 1720951200,
            time: "2024-07-14 12:00",
            temp_c: 28,
            temp_f: 82.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 220,
            wind_dir: "SW",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 56,
            cloud: 14,
            feelslike_c: 29.3,
            feelslike_f: 84.7,
            windchill_c: 28,
            windchill_f: 82.4,
            heatindex_c: 29.3,
            heatindex_f: 84.7,
            dewpoint_c: 18.3,
            dewpoint_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.4,
            gust_kph: 7.1,
            uv: 7,
            short_rad: 645.26,
            diff_rad: 110.2,
          },
          {
            time_epoch: 1720954800,
            time: "2024-07-14 13:00",
            temp_c: 28.7,
            temp_f: 83.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 204,
            wind_dir: "SSW",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 50,
            cloud: 7,
            feelslike_c: 29.7,
            feelslike_f: 85.4,
            windchill_c: 28.8,
            windchill_f: 83.8,
            heatindex_c: 29.7,
            heatindex_f: 85.4,
            dewpoint_c: 17.2,
            dewpoint_f: 63,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 7,
            short_rad: 686.85,
            diff_rad: 112.46,
          },
          {
            time_epoch: 1720958400,
            time: "2024-07-14 14:00",
            temp_c: 29,
            temp_f: 84.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 205,
            wind_dir: "SSW",
            pressure_mb: 1012,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 47,
            cloud: 5,
            feelslike_c: 29.7,
            feelslike_f: 85.5,
            windchill_c: 29,
            windchill_f: 84.3,
            heatindex_c: 29.7,
            heatindex_f: 85.5,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 7,
            short_rad: 839.3,
            diff_rad: 203.52,
          },
          {
            time_epoch: 1720962000,
            time: "2024-07-14 15:00",
            temp_c: 29,
            temp_f: 84.3,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 200,
            wind_dir: "SSW",
            pressure_mb: 1011,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 47,
            cloud: 58,
            feelslike_c: 29.7,
            feelslike_f: 85.5,
            windchill_c: 29,
            windchill_f: 84.3,
            heatindex_c: 29.7,
            heatindex_f: 85.5,
            dewpoint_c: 16.5,
            dewpoint_f: 61.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 7,
            short_rad: 777.44,
            diff_rad: 232.67,
          },
          {
            time_epoch: 1720965600,
            time: "2024-07-14 16:00",
            temp_c: 29,
            temp_f: 84.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 201,
            wind_dir: "SSW",
            pressure_mb: 1011,
            pressure_in: 29.86,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 47,
            cloud: 4,
            feelslike_c: 29.7,
            feelslike_f: 85.5,
            windchill_c: 29,
            windchill_f: 84.2,
            heatindex_c: 29.7,
            heatindex_f: 85.5,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.5,
            uv: 7,
            short_rad: 725.8,
            diff_rad: 224.43,
          },
          {
            time_epoch: 1720969200,
            time: "2024-07-14 17:00",
            temp_c: 28.7,
            temp_f: 83.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 195,
            wind_dir: "SSW",
            pressure_mb: 1011,
            pressure_in: 29.86,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 49,
            cloud: 8,
            feelslike_c: 29.6,
            feelslike_f: 85.2,
            windchill_c: 28.7,
            windchill_f: 83.7,
            heatindex_c: 29.6,
            heatindex_f: 85.2,
            dewpoint_c: 17.1,
            dewpoint_f: 62.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.8,
            uv: 7,
            short_rad: 674.12,
            diff_rad: 196.47,
          },
          {
            time_epoch: 1720972800,
            time: "2024-07-14 18:00",
            temp_c: 27.8,
            temp_f: 82.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 201,
            wind_dir: "SSW",
            pressure_mb: 1011,
            pressure_in: 29.86,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 58,
            cloud: 14,
            feelslike_c: 29.3,
            feelslike_f: 84.8,
            windchill_c: 27.9,
            windchill_f: 82.1,
            heatindex_c: 29.3,
            heatindex_f: 84.8,
            dewpoint_c: 18.9,
            dewpoint_f: 66.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.2,
            gust_kph: 8.4,
            uv: 7,
            short_rad: 605.33,
            diff_rad: 180.64,
          },
          {
            time_epoch: 1720976400,
            time: "2024-07-14 19:00",
            temp_c: 26,
            temp_f: 78.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 213,
            wind_dir: "SSW",
            pressure_mb: 1012,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 68,
            cloud: 10,
            feelslike_c: 27.7,
            feelslike_f: 81.9,
            windchill_c: 26.1,
            windchill_f: 78.9,
            heatindex_c: 27.7,
            heatindex_f: 81.9,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.6,
            uv: 7,
            short_rad: 535.46,
            diff_rad: 159.62,
          },
          {
            time_epoch: 1720980000,
            time: "2024-07-14 20:00",
            temp_c: 24.2,
            temp_f: 75.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 239,
            wind_dir: "WSW",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 73,
            cloud: 11,
            feelslike_c: 25.9,
            feelslike_f: 78.6,
            windchill_c: 24.2,
            windchill_f: 75.5,
            heatindex_c: 25.9,
            heatindex_f: 78.6,
            dewpoint_c: 19,
            dewpoint_f: 66.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 6,
            short_rad: 43.96,
            diff_rad: 19.45,
          },
          {
            time_epoch: 1720983600,
            time: "2024-07-14 21:00",
            temp_c: 23.5,
            temp_f: 74.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 268,
            wind_dir: "W",
            pressure_mb: 1012,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 75,
            cloud: 2,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 23.6,
            windchill_f: 74.4,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.5,
            uv: 6,
            short_rad: 22.02,
            diff_rad: 9.74,
          },
          {
            time_epoch: 1720987200,
            time: "2024-07-14 22:00",
            temp_c: 23.1,
            temp_f: 73.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 304,
            wind_dir: "NW",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 3,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.1,
            windchill_f: 73.5,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 18.7,
            dewpoint_f: 65.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 0,
            short_rad: 14.68,
            diff_rad: 6.5,
          },
          {
            time_epoch: 1720990800,
            time: "2024-07-14 23:00",
            temp_c: 22.6,
            temp_f: 72.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 308,
            wind_dir: "NW",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 4,
            feelslike_c: 24.8,
            feelslike_f: 76.7,
            windchill_c: 22.6,
            windchill_f: 72.8,
            heatindex_c: 24.8,
            heatindex_f: 76.7,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 0,
            short_rad: 11.02,
            diff_rad: 4.87,
          },
        ],
      },
      {
        date: "2024-07-15",
        date_epoch: 1721001600,
        day: {
          maxtemp_c: 30.2,
          maxtemp_f: 86.4,
          mintemp_c: 20.2,
          mintemp_f: 68.4,
          avgtemp_c: 25.3,
          avgtemp_f: 77.5,
          maxwind_mph: 4.9,
          maxwind_kph: 7.9,
          totalprecip_mm: 0.01,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 69,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 8,
        },
        astro: {
          sunrise: "05:50 AM",
          sunset: "09:09 PM",
          moonrise: "03:38 PM",
          moonset: "12:51 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: 60,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1720994400,
            time: "2024-07-15 00:00",
            temp_c: 22.2,
            temp_f: 71.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 81,
            cloud: 4,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.2,
            windchill_f: 71.9,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 18.9,
            dewpoint_f: 66,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.5,
            gust_kph: 8.8,
            uv: 0,
            short_rad: 8.82,
            diff_rad: 3.9,
          },
          {
            time_epoch: 1720998000,
            time: "2024-07-15 01:00",
            temp_c: 21.7,
            temp_f: 71.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 281,
            wind_dir: "WNW",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 84,
            cloud: 4,
            feelslike_c: 21.7,
            feelslike_f: 71.1,
            windchill_c: 21.7,
            windchill_f: 71.1,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 8,
            uv: 0,
            short_rad: 7.34,
            diff_rad: 3.25,
          },
          {
            time_epoch: 1721001600,
            time: "2024-07-15 02:00",
            temp_c: 21.3,
            temp_f: 70.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 266,
            wind_dir: "W",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 84,
            cloud: 4,
            feelslike_c: 21.3,
            feelslike_f: 70.4,
            windchill_c: 21.3,
            windchill_f: 70.4,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1721005200,
            time: "2024-07-15 03:00",
            temp_c: 20.9,
            temp_f: 69.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 298,
            wind_dir: "WNW",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 85,
            cloud: 4,
            feelslike_c: 20.9,
            feelslike_f: 69.6,
            windchill_c: 20.9,
            windchill_f: 69.6,
            heatindex_c: 20.9,
            heatindex_f: 69.6,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.7,
            gust_kph: 4.3,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1721008800,
            time: "2024-07-15 04:00",
            temp_c: 20.5,
            temp_f: 68.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 322,
            wind_dir: "NW",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 85,
            cloud: 4,
            feelslike_c: 20.5,
            feelslike_f: 68.8,
            windchill_c: 20.5,
            windchill_f: 68.8,
            heatindex_c: 20.5,
            heatindex_f: 68.8,
            dewpoint_c: 17.8,
            dewpoint_f: 64.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.8,
            gust_kph: 2.9,
            uv: 0,
            short_rad: 0,
            diff_rad: 0,
          },
          {
            time_epoch: 1721012400,
            time: "2024-07-15 05:00",
            temp_c: 20.2,
            temp_f: 68.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 0.4,
            wind_kph: 0.7,
            wind_degree: 11,
            wind_dir: "NNE",
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 85,
            cloud: 4,
            feelslike_c: 20.2,
            feelslike_f: 68.4,
            windchill_c: 20.2,
            windchill_f: 68.4,
            heatindex_c: 20.2,
            heatindex_f: 68.4,
            dewpoint_c: 17.7,
            dewpoint_f: 63.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.9,
            gust_kph: 1.4,
            uv: 0,
            short_rad: 0.05,
            diff_rad: 0.02,
          },
          {
            time_epoch: 1721016000,
            time: "2024-07-15 06:00",
            temp_c: 21.1,
            temp_f: 69.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 0.4,
            wind_kph: 0.7,
            wind_degree: 60,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 84,
            cloud: 4,
            feelslike_c: 21.1,
            feelslike_f: 69.9,
            windchill_c: 21.1,
            windchill_f: 69.9,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 18.3,
            dewpoint_f: 65,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.8,
            gust_kph: 1.2,
            uv: 6,
            short_rad: 9.49,
            diff_rad: 4.15,
          },
          {
            time_epoch: 1721019600,
            time: "2024-07-15 07:00",
            temp_c: 22.5,
            temp_f: 72.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 106,
            wind_dir: "ESE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 4,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.5,
            windchill_f: 72.5,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.5,
            gust_kph: 2.4,
            uv: 6,
            short_rad: 39.09,
            diff_rad: 13.4,
          },
          {
            time_epoch: 1721023200,
            time: "2024-07-15 08:00",
            temp_c: 23.8,
            temp_f: 74.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 129,
            wind_dir: "SE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 74,
            cloud: 6,
            feelslike_c: 25.6,
            feelslike_f: 78.1,
            windchill_c: 23.8,
            windchill_f: 74.9,
            heatindex_c: 25.6,
            heatindex_f: 78.1,
            dewpoint_c: 19,
            dewpoint_f: 66.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.7,
            gust_kph: 4.4,
            uv: 6,
            short_rad: 340.18,
            diff_rad: 111.02,
          },
          {
            time_epoch: 1721026800,
            time: "2024-07-15 09:00",
            temp_c: 25.3,
            temp_f: 77.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 128,
            wind_dir: "SE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 70,
            cloud: 11,
            feelslike_c: 26.9,
            feelslike_f: 80.5,
            windchill_c: 25.3,
            windchill_f: 77.5,
            heatindex_c: 26.9,
            heatindex_f: 80.5,
            dewpoint_c: 19.4,
            dewpoint_f: 67,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 7,
            short_rad: 424.24,
            diff_rad: 123.68,
          },
          {
            time_epoch: 1721030400,
            time: "2024-07-15 10:00",
            temp_c: 26.7,
            temp_f: 80.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 116,
            wind_dir: "ESE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 65,
            cloud: 6,
            feelslike_c: 28.3,
            feelslike_f: 83,
            windchill_c: 26.7,
            windchill_f: 80.1,
            heatindex_c: 28.3,
            heatindex_f: 83,
            dewpoint_c: 19.6,
            dewpoint_f: 67.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 7,
            short_rad: 501.78,
            diff_rad: 134.67,
          },
          {
            time_epoch: 1721034000,
            time: "2024-07-15 11:00",
            temp_c: 27.9,
            temp_f: 82.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 117,
            wind_dir: "ESE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 60,
            cloud: 5,
            feelslike_c: 29.6,
            feelslike_f: 85.2,
            windchill_c: 27.9,
            windchill_f: 82.2,
            heatindex_c: 29.6,
            heatindex_f: 85.2,
            dewpoint_c: 19.4,
            dewpoint_f: 67,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 7,
            short_rad: 574.24,
            diff_rad: 129.26,
          },
          {
            time_epoch: 1721037600,
            time: "2024-07-15 12:00",
            temp_c: 28.8,
            temp_f: 83.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 122,
            wind_dir: "ESE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 55,
            cloud: 5,
            feelslike_c: 30.4,
            feelslike_f: 86.7,
            windchill_c: 28.8,
            windchill_f: 83.9,
            heatindex_c: 30.4,
            heatindex_f: 86.7,
            dewpoint_c: 18.9,
            dewpoint_f: 66.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.7,
            uv: 7,
            short_rad: 632.12,
            diff_rad: 126.47,
          },
          {
            time_epoch: 1721041200,
            time: "2024-07-15 13:00",
            temp_c: 29.6,
            temp_f: 85.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 127,
            wind_dir: "SE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 52,
            cloud: 5,
            feelslike_c: 31.1,
            feelslike_f: 87.9,
            windchill_c: 29.6,
            windchill_f: 85.2,
            heatindex_c: 31.1,
            heatindex_f: 87.9,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.7,
            gust_kph: 9.1,
            uv: 7,
            short_rad: 674.51,
            diff_rad: 124.68,
          },
          {
            time_epoch: 1721044800,
            time: "2024-07-15 14:00",
            temp_c: 30.1,
            temp_f: 86.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 133,
            wind_dir: "SE",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 50,
            cloud: 5,
            feelslike_c: 31.7,
            feelslike_f: 89,
            windchill_c: 30.1,
            windchill_f: 86.1,
            heatindex_c: 31.7,
            heatindex_f: 89,
            dewpoint_c: 18.6,
            dewpoint_f: 65.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.7,
            gust_kph: 9.1,
            uv: 8,
            short_rad: 859.18,
            diff_rad: 113.99,
          },
          {
            time_epoch: 1721048400,
            time: "2024-07-15 15:00",
            temp_c: 30.2,
            temp_f: 86.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 130,
            wind_dir: "SE",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 49,
            cloud: 5,
            feelslike_c: 31.7,
            feelslike_f: 89.1,
            windchill_c: 30.3,
            windchill_f: 86.5,
            heatindex_c: 31.7,
            heatindex_f: 89.1,
            dewpoint_c: 18.4,
            dewpoint_f: 65.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.7,
            uv: 8,
            short_rad: 822.06,
            diff_rad: 111.06,
          },
          {
            time_epoch: 1721052000,
            time: "2024-07-15 16:00",
            temp_c: 30.2,
            temp_f: 86.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 126,
            wind_dir: "SE",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 49,
            cloud: 5,
            feelslike_c: 31.6,
            feelslike_f: 88.9,
            windchill_c: 30.2,
            windchill_f: 86.3,
            heatindex_c: 31.6,
            heatindex_f: 88.9,
            dewpoint_c: 18.3,
            dewpoint_f: 65,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.5,
            gust_kph: 8.9,
            uv: 8,
            short_rad: 771.16,
            diff_rad: 107.25,
          },
          {
            time_epoch: 1721055600,
            time: "2024-07-15 17:00",
            temp_c: 29.8,
            temp_f: 85.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 128,
            wind_dir: "SE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 51,
            cloud: 4,
            feelslike_c: 31.3,
            feelslike_f: 88.4,
            windchill_c: 29.8,
            windchill_f: 85.7,
            heatindex_c: 31.3,
            heatindex_f: 88.4,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 7,
            short_rad: 708.61,
            diff_rad: 102.58,
          },
          {
            time_epoch: 1721059200,
            time: "2024-07-15 18:00",
            temp_c: 29,
            temp_f: 84.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 134,
            wind_dir: "SE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 57,
            cloud: 3,
            feelslike_c: 30.9,
            feelslike_f: 87.6,
            windchill_c: 29,
            windchill_f: 84.2,
            heatindex_c: 30.9,
            heatindex_f: 87.6,
            dewpoint_c: 19.7,
            dewpoint_f: 67.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.7,
            uv: 7,
            short_rad: 637.46,
            diff_rad: 96.86,
          },
          {
            time_epoch: 1721062800,
            time: "2024-07-15 19:00",
            temp_c: 27.3,
            temp_f: 81.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 132,
            wind_dir: "SE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 68,
            cloud: 4,
            feelslike_c: 29.4,
            feelslike_f: 84.9,
            windchill_c: 27.3,
            windchill_f: 81.1,
            heatindex_c: 29.4,
            heatindex_f: 84.9,
            dewpoint_c: 20.8,
            dewpoint_f: 69.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.4,
            gust_kph: 7.1,
            uv: 7,
            short_rad: 561.81,
            diff_rad: 89.46,
          },
          {
            time_epoch: 1721066400,
            time: "2024-07-15 20:00",
            temp_c: 25.4,
            temp_f: 77.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 142,
            wind_dir: "SE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 72,
            cloud: 6,
            feelslike_c: 27.2,
            feelslike_f: 80.9,
            windchill_c: 25.4,
            windchill_f: 77.8,
            heatindex_c: 27.2,
            heatindex_f: 80.9,
            dewpoint_c: 20,
            dewpoint_f: 67.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.8,
            gust_kph: 2.9,
            uv: 7,
            short_rad: 42.7,
            diff_rad: 18.9,
          },
          {
            time_epoch: 1721070000,
            time: "2024-07-15 21:00",
            temp_c: 24.7,
            temp_f: 76.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 0.7,
            wind_kph: 1.1,
            wind_degree: 31,
            wind_dir: "NNE",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 73,
            cloud: 9,
            feelslike_c: 26.4,
            feelslike_f: 79.5,
            windchill_c: 24.7,
            windchill_f: 76.4,
            heatindex_c: 26.4,
            heatindex_f: 79.5,
            dewpoint_c: 19.5,
            dewpoint_f: 67,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.4,
            gust_kph: 2.3,
            uv: 6,
            short_rad: 21.38,
            diff_rad: 9.46,
          },
          {
            time_epoch: 1721073600,
            time: "2024-07-15 22:00",
            temp_c: 24.2,
            temp_f: 75.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 315,
            wind_dir: "NW",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 75,
            cloud: 12,
            feelslike_c: 26,
            feelslike_f: 78.8,
            windchill_c: 24.2,
            windchill_f: 75.6,
            heatindex_c: 26,
            heatindex_f: 78.8,
            dewpoint_c: 19.4,
            dewpoint_f: 67,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.2,
            uv: 0,
            short_rad: 14.26,
            diff_rad: 6.31,
          },
          {
            time_epoch: 1721077200,
            time: "2024-07-15 23:00",
            temp_c: 23.9,
            temp_f: 75,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 347,
            wind_dir: "NNW",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 87,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 23.9,
            windchill_f: 75,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 19.6,
            dewpoint_f: 67.2,
            will_it_rain: 1,
            chance_of_rain: 86,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5,
            gust_kph: 8.1,
            uv: 0,
            short_rad: 10.68,
            diff_rad: 4.74,
          },
        ],
      },
    ],
  },
};
